/* EVERY FILE IN game/assets, AGAINST EVERY WAY THE GAME COULD ASK FOR IT.
 *
 * An asset nobody references is still downloaded, still in the deploy, and still in the
 * repository. Two have shipped that way already:
 *
 *   assets/prgrass bar/*.png     3.8MB of raw art dropped in the wrong folder
 *   assets/option-shape/image.png 1.3MB, the same mistake a week later
 *
 * Both were invisible to the eye because game/assets is 17MB of legitimate art, and
 * both were invisible to a first attempt at this check because it asked "does the
 * filename appear anywhere in the source" — and "image" appears in a hundred places.
 * A stem test is useless for a generic name, which is exactly the name a stray file
 * has. So this matches on the PATH the game would load, and on the exact filename, and
 * nothing looser.
 *
 * asset-versions.js is excluded as evidence: it is generated by walking this folder, so
 * every file appears in it whether or not anything wants it. That file is what made the
 * two above look referenced.
 *
 * DYNAMIC NAMES are the one thing a scanner cannot see — `'assets/env/obs-' + kind`
 * builds a path that is never written down. Those are listed separately rather than
 * reported as orphans, so a human decides. Keep the list short and the construction
 * obvious, or this check stops being able to help.
 *
 *   node tools/check-assets.mjs          # report
 *   node tools/check-assets.mjs --strict # exit 1 if anything is unreferenced
 */
import { readdirSync, statSync, readFileSync } from 'node:fs';
import { join, relative, basename } from 'node:path';

const ASSETS = 'game/assets';
const strict = process.argv.includes('--strict');

const walk = d => readdirSync(d, { withFileTypes: true }).flatMap(e => {
  const p = join(d, e.name);
  return e.isDirectory() ? walk(p) : [p];
});

/* TWO HAYSTACKS, AND THE DIFFERENCE BETWEEN THEM IS THE POINT.
 *
 * `hay` is everywhere the RUNNING GAME could name a path: its modules, its stylesheets,
 * its page. NOT the generated manifest, and NOT the bundle, which is a copy of the
 * modules. If a path is not in here, no browser ever requests the file.
 *
 * `toolHay` is the tools, which name the files they PRODUCE. That is a different claim
 * entirely, and folding it into `hay` is what let three dead files hide: the jump
 * button's normal/pressed pair and TRY AGAIN outlived the controls they belonged to,
 * but make-buttons.mjs still named them as its outputs, so this check called all three
 * "referenced" and reported a clean run while 149KB shipped to every visitor. A build
 * recipe is evidence that a file CAN be produced, never that anything loads it. */
const gameSources = [
  ...walk('game/js').filter(f => f.endsWith('.js') &&
    !f.endsWith('asset-versions.js') && !f.endsWith('game.bundle.js')),
  ...walk('game/css').filter(f => f.endsWith('.css')),
  'game/index.html'
];
const toolSources = walk('tools').filter(f => f.endsWith('.mjs') && !f.endsWith('check-assets.mjs'));
const hay = gameSources.map(f => readFileSync(f, 'utf8')).join('\n');
const toolHay = toolSources.map(f => readFileSync(f, 'utf8')).join('\n');

/** Does a haystack name this file, by exact path or exact quoted basename? */
const names = (h, rel, name) => h.includes(rel) || h.includes('/' + name) ||
  h.includes("'" + name + "'") || h.includes('"' + name + '"');

/* Families the game builds a path for at run time. Each is a folder plus the prefix the
   code concatenates onto; anything matching is credited to the line that builds it. */
const DYNAMIC = [
  { dir: 'assets/env', prefix: 'obs-', built: "engine.js: 'assets/env/obs-' + kind" },
  /* Only .webp: the delivered shapes are all webp, so a .png in this folder is a
     source file somebody dropped in the wrong place — which is exactly how a 1.3MB
     image.png shipped. A rule that credits a whole FOLDER is the same loose matching
     this check exists to replace. */
  { dir: 'assets/option-shape', only: '.webp', built: 'option-shapes.js: one webp per polygon name' },
  { dir: 'assets/sky', prefix: '', built: 'engine.js: the sky set, keyed by time of day' },
  /* EVERY SOUND SHIPS TWICE and only the mp3 is ever written down: assetUrl() swaps the
     extension when the browser can take ogg (Safari under 17.4 cannot, so both are
     needed). The first run of this check called all ten oggs unreferenced — 2.4MB of
     "waste" that is nothing of the kind. A twin counts as referenced only if its mp3 is. */
  { ext: '.ogg', twin: '.mp3', built: 'engine.js assetUrl(): the .mp3 with its extension swapped' },
  /* AND SOME PICTURES SHIP TWICE (tools/build-avif.mjs): assetUrl() asks for the .avif beside a
     .webp where the browser shows AVIF. The same rule: a twin counts only if its .webp does. */
  { ext: '.avif', twin: '.webp', built: "engine.js assetUrl(): the .webp's AVIF twin" }
];

const orphans = [], dynamic = [], toolOnly = [];
let total = 0, orphanBytes = 0;

for (const file of walk(ASSETS)) {
  // the user's Hindi recordings (assets/vo-part-2-hindi/*.opus): the source of vo-lines-hi, kept out
  // of the deploy by .vercelignore — not served, so not an asset
  if (/\.(wav|opus)$/i.test(file)) continue;
  const rel = relative('game', file).split('\\').join('/');
  const name = basename(file);
  total++;
  // the exact path, or the exact filename in quotes — nothing looser
  if (names(hay, rel, name)) continue;

  const dyn = DYNAMIC.find(d => {
    /* A twin is credited only if the file it is a twin OF is actually referenced —
       otherwise an orphan mp3 would quietly license an orphan ogg beside it. */
    if (d.ext) {
      if (!rel.endsWith(d.ext)) return false;
      const src = rel.slice(0, -d.ext.length) + d.twin;
      return names(hay, src, basename(src));
    }
    if (d.only && !rel.endsWith(d.only)) return false;
    return rel.startsWith(d.dir + '/') && (!d.prefix || name.startsWith(d.prefix));
  });
  const size = statSync(file).size;
  if (dyn) { dynamic.push({ rel, size, by: dyn.built }); continue; }
  /* Named by a build recipe and by nothing the game loads: still shipped, still
     downloaded, just with a tool that knows how to rebuild it. Called out on its own
     line rather than counted clean, because that is exactly how it hides. */
  if (names(toolHay, rel, name)) { toolOnly.push({ rel, size }); orphanBytes += size; continue; }
  orphans.push({ rel, size });
  orphanBytes += size;
}

const kb = n => (n / 1024).toFixed(0).padStart(6) + ' KB';

console.log(`${total} assets in ${ASSETS}\n`);
if (dynamic.length) {
  console.log(`${dynamic.length} loaded by a path built at run time (not orphans):`);
  const by = {};
  for (const d of dynamic) (by[d.by] ||= []).push(d);
  for (const [built, list] of Object.entries(by)) {
    console.log(`  ${list.length} files — ${built}`);
  }
  console.log('');
}
if (toolOnly.length) {
  console.log(`${toolOnly.length} BUILD OUTPUT ONLY — a tool writes these, nothing in the game loads them:`);
  for (const o of toolOnly.sort((a, b) => b.size - a.size)) console.log(`  ${kb(o.size)}  ${o.rel}`);
  console.log('  Keep the recipe in tools/ if the art may come back; the OUTPUT does not belong here.\n');
}
if (orphans.length) {
  console.log(`${orphans.length} UNREFERENCED — nothing in the game asks for these:`);
  for (const o of orphans.sort((a, b) => b.size - a.size)) console.log(`  ${kb(o.size)}  ${o.rel}`);
  console.log('  Source art belongs in art-source/, which is outside the deployed folder.\n');
}
if (orphans.length || toolOnly.length) {
  console.log(`  ${(orphanBytes / 1024 / 1024).toFixed(2)} MB shipped for nothing.`);
} else {
  console.log('No unreferenced assets. Everything in game/assets is loaded by the game itself.');
}

if (strict && (orphans.length || toolOnly.length)) process.exit(1);
