/* generated by tools/build-story.js from assets/source/story — do not edit by hand */
window.StoryArt = {
  "w": 1672,
  "h": 941,
  "around": {
    "x": 480,
    "y": 380
  },
  "scenes": [
    {
      "src": "assets/story/scene-1.webp?v=cb161bb4",
      "around": "assets/story/scene-1-around.webp?v=0789fd7e"
    },
    {
      "src": "assets/story/scene-2.webp?v=23effb28",
      "around": "assets/story/scene-2-around.webp?v=1a8875f5"
    },
    {
      "src": "assets/story/scene-3.webp?v=d1ae0b8d",
      "around": "assets/story/scene-3-around.webp?v=2fe2df6f"
    },
    {
      "src": "assets/story/scene-4.webp?v=bd6638e6",
      "around": "assets/story/scene-4-around.webp?v=ef7dbf0e"
    },
    {
      "src": "assets/story/scene-5.webp?v=f22b7dd7",
      "around": "assets/story/scene-5-around.webp?v=89454de0"
    }
  ]
};
